config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'top#top'
  resources :tables do
    member do
      get 'clone'
    end
  end
  resources :works
  resources :taxons, only: [:show]
  get 'search_table' => 'tables#search'
  get 'search_work' => 'works#search'
  get 'usage' => 'top#usage'
  post 'guest_sign_in' => 'top#guest_sign_in'
end

app/views/shared/_error.html.slim
.validation_error_message_area
  - if obj.errors.any?
    - obj.errors.full_messages.each do |message|
      ul.validation_error_message
        li
          = message

app/views/shared/_search_results.html.slim
.centered
  - if flash[:search_results]
    p.search_results
      = flash[:search_results]

app/views/shared/_side_bar.html.slim
#side_bar
  .side_bar_title
    | カテゴリ
  .side_bar_link
    ul
      li
        = link_to works_path, data: {"turbolinks" => false} do
          |  全業務 
      - taxons.each do |taxon|
        li
          = link_to taxon_path(taxon.id), id: "taxon_#{taxon.id}", data: {"turbolinks" => false} do
            = taxon.name

app/views/shared/_works_index.html.slim
.centered
  table.works_index
    thead
      tr
        th
          = sort_order "id", "id"
        th
          = sort_order "name", "業務名"
        th
          = sort_order "time_required", "所要時間（分）"
        th
          | カテゴリ
        th
          = sort_order "updated_at", "更新日"
        th
          | 編集
        th
          | 削除
    tbody
      - works.each do |work|
        tr
          td
            = work.id
          td
            = work.name
          td
            = work.time_required
          td
            = work.taxon.name
          td
            = work.updated_at.to_s(:datetime_jp_short)
          td
            = link_to "編集", edit_work_path(work.id), class: "color_blue", id: "edit_work_#{work.id}", data: {"turbolinks" => false}
          td
            = link_to "削除", work_path(work.id), method: :delete, data: { confirm: "本当に削除しますか？", "turbolinks" => false }, class: "color_blue", id: "delete_work_#{work.id}"