config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'top#top'
  resources :tables do
    member do
      get 'clone'
    end
  end
  resources :works
  resources :taxons, only: [:show]
  get 'search_table' => 'tables#search'
  get 'search_work' => 'works#search'
  get 'usage' => 'top#usage'
  post 'guest_sign_in' => 'top#guest_sign_in'
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  SAMPLE_TABLE = Table.new(
    title: 'サンプルデータ',
    cells: [
      '6:00', '仮点検　(10分)', '', '缶ウォーマー補充　(5分)', '', '', '', '', 'HCケース補充　(20分)', '',
      '', '', '', 'フェイスアップ　(15分)', '', '', '', '', 'フライヤー仕込み　(30分)', '',
      '7:00', '温度点検　(10分)', '', 'おでん仕込み　(20分)', '', '', '', '', '中華まん仕込み　(10分)', '',
      '8:00', '', '', '発注：米飯　(20分)', 'トイレ清掃　(15分)', '', '', '', '発注：調理パン　(10分)', '床清掃　(10分)',
      '', '', '', '発注：ペストリー　(20分)', 'レジカウンター清掃　(10分)', '', '仮点検　(10分)', '', '', '',
      '9:00', '', '米飯2便納品　(30分)', '', '', '', '', 'チルド2便納品　(30分)', '', '',
      '10:00', '', '', 'フェイスアップ　(15分)', '店外清掃　(20分)', '', '', '', '販売データ確認　(20分)', 'コピー機清掃　(10分)',
      '', '', '', '', 'ATM清掃　(5分)',
      '11:00', '鮮度管理　(15分)', '', 'フライヤー追加仕込み　(15分)', '', '', '', '', 'カウンター消耗品補充　(15分)', '',
      '12:00', 'ピーク対応', '', '', '',
      '13:00', '売上日報　(60分)', '', '', 'ゴミ袋交換　(10分)', '', '', '', '', 'トイレ清掃　(15分)', '', '', '', '', '床清掃　(10分)',
      '14:00', '鮮度管理　(15分)', '', 'フェイスアップ　(15分)', 'チルドケース清掃　(20分)', '', 'ATM入金　(10分)', '', '', '',
      '15:00', '', '米飯3便納品　(30分)', '', '', '', '', 'チルド3便納品　(30分)', '', '', '', '', 'オリジナルパン3便納品　(15分)', '', '',
      '16:00', '', '', 'フライヤー仕込み　(30分)', '', '', '', '', '商品補充：菓子　(30分)', '',
      '17:00', '仮点検　(10分)', '', '商品補充：加食　(15分)', '店外清掃　(10分)', '', '', '', '商品補充：雑貨　(15分)', '',
      '', '', '', 'フェイスアップ　(15分)', '',
      '18:00', 'ATM入金　(10分)', '', '週3菓子納品　(60分)', '', '', '伝票集計　(20分)', '', '', '',
      '19:00', '鮮度管理　(15分)', '', '雑誌返本　(30分)', 'リーチイン清掃　(10分)', '', '', '', '', 'アイスケース清掃　(10分)',
      '20:00', '', '', '販売データ確認　(20分)', 'ゴミ袋交換　(10分)', '', '', '', '死筋排除　(40分)', 'トイレ清掃　(15分)',
      '', '', '', '', '床清掃　(10分)',
      '21:00', '', '', '発注：サラダ・惣菜　(20分)', '', '', '', '', '発注：調理麺　(15分)', '', '', '', '', '発注：牛乳・乳飲料　(20分)', '',
      '22:00', '仮点検　(10分)', '米飯1便納品　(30分)', '', '発注：加食　(5分)', '', 'ATM入金　(10分)', '', '発注：雑貨　(5分)', '',
      '23:00', '鮮度管理　(15分)', '', '新聞返品処理　(15分)', '', '', '', '', 'フェイスアップ　(15分)', '', '', '', '', 'フライヤー電源OFF　(1分)', '',
      '0:00', 'ストアスタンプ日付変更　(2分)', '', 'おでんスープ交換　(20分)', '',
      '1:00', '深夜鮮度管理　(45分)', '', '商品補充：ソフトドリンク　(30分)', '',
      '2:00', '', 'チルド1便納品　(60分)', '', 'おでん什器清掃　(20分)', '', '', '', '', 'フライヤー什器清掃　(20分)',
      '', '', '', '', '常温フライヤー什器清掃　(20分)',
      '3:00', '', 'オリジナルパン1便納品　(30分)', '', '中華まん什器清掃　(20分)', '', '', '', '', 'フライヤー本体清掃　(40分)',
      '4:00', '', '山崎パン1便納品　(10分)', '', 'グリストラップ清掃　(20分)', '', '', '雑誌納品　(45分)', '', '',
      '5:00', '温度点検　(10分)', 'フローズン納品　(20分)', '', '', '', '', '新聞納品　(15分)', '', ''
    ],
    size: 57
  )

  TABLE_INITIAL_VALUE = Table.new(
    cells: [
      '6:00', '', '', '', '', '7:00', '温度点検　(10分)', '', '', '', '8:00', '', '', '', '', '9:00', '', '', '', '',
      '10:00', '', '', '', '', '11:00', '鮮度管理　(15分)', '', '', '', '12:00', '', '', '', '', '13:00', '', '', '', '',
      '14:00', '鮮度管理　(15分)', '', '', '', '15:00', '', '', '', '', '16:00', '', '', '', '', '17:00', '', '', '', '',
      '18:00', '', '', '', '', '19:00', '鮮度管理　(15分)', '', '', '', '20:00', '', '', '', '', '21:00', '', '', '', '',
      '22:00', '', '', '', '', '23:00', '鮮度管理　(15分)', '', '', '', '0:00', 'ストアスタンプ日付変更　(2分)', '', '', '',
      '1:00', '深夜鮮度管理　(45分)', '', '', '', '2:00', '', '', '', '', '3:00', '', '', '', '', '4:00', '', '', '', '',
      '5:00', '温度点検　(10分)', '', '', ''
    ],
    size: 24
  )

  layout 'tables_show', only: :show
  before_action :authenticate_user!
  before_action :set_each_works, only: %i[new edit]
  before_action :table_owner?, only: %i[show edit update destroy]
  before_action :set_params_cells, only: %i[create update]

  def index
    @tables = Table.owner(current_user).order("#{sort_column} #{sort_direction}")
    flash[:search_results] = nil
  end

  def new
    @table = params[:call_sample] ? SAMPLE_TABLE : TABLE_INITIAL_VALUE
  end

  def create
    @table = current_user.tables.new(title: params[:title], cells: @params_cells, size: params[:table_size])
    if @table.save
      flash[:notice] = '作業割当を新規登録しました'
      redirect_to :tables
    else
      render 'new'
    end
  end

  def show
    @rows = @table.cells.each_slice(5).to_a
  end

  def edit; end

  def update
    if @table.update(title: params[:title], cells: @params_cells, size: params[:table_size])
      flash[:notice] = "IDが「#{@table.id}」の作業割当を更新しました"
      redirect_to :tables
    else
      render 'edit'
    end
  end

  def clone
    @old_table = Table.find(params[:id])
    @table = @old_table.dup
    @table.save
    @table.update(title: "#{@table.title}(コピー)")
    flash[:notice] = "IDが「#{@old_table.id}」の作業割当を複製しました"
    redirect_to :tables
  end

  def destroy
    @table.destroy
    flash[:notice] = '作業割当を削除しました'
    redirect_to :tables
  end

  def search
    if params[:keyword].present?
      @tables = Table.owner(current_user).order("#{sort_column} #{sort_direction}").search_results(params[:keyword])
      flash[:search_results] = "検索結果：#{@tables.count}件"
      render 'index'
    else
      redirect_to :tables
    end
  end

  private

  def set_each_works
    @regular_works = Work.owner(current_user).category(1).order(:name)
    @deliver_works = Work.owner(current_user).category(2).order(:name)
    @product_management_works = Work.owner(current_user).category(3).order(:name)
    @cleaning_works = Work.owner(current_user).category(4).order(:name)
  end

  def table_owner?
    @table = Table.find(params[:id])
    redirect_to root_path unless @table.user_id == current_user.id
  end

  def set_params_cells
    cells_length = params[:cells_length].to_i
    @params_cells = []
    cells_length.times do |num|
      @params_cells.push(params["cell#{num}"])
    end
  end

  def sort_column
    params[:sort] || 'updated_at'
  end

  def sort_direction
    params[:direction] || 'desc'
  end
end

app/views/tables/_form.html.slim
.centered
  table.sagyouwariate#sagyouwariate
    thead
      tr
        th.th_short style="color:green"
          | 行追加
        th.th_short style="color:#b84543"
          | 行削除
        th.th_time
          | 時間
        th
          | 定時業務
        th
          | 納品業務
        th
          | 商品管理業務
        th
          | 清掃業務
    tbody
      - table.size.times do |num|
        tr
          td
            input type="button" value="↪︎+" onclick="insertRow(this)" id="insert_row_#{num}" class="insert_row" title="下に1行挿入"
          td
            input type="button" value="×→" onclick="deleteRow(this)" class="delete_row" title="この行を削除"
          td
            = f.text_field "cell#{num * 5 + 0}".to_sym, class: "cell", value: table.cells[num * 5 + 0], :size=>"5"
          td
            = f.text_field "cell#{num * 5 + 1}".to_sym, list: "regular_work", class: "cell", value: table.cells[num * 5 + 1], :size=>"28"
            datalist#regular_work
              - @regular_works.each do |regular_work|
                |  <option value="
                = regular_work.name
                | 　(
                = regular_work.time_required
                | 分)">
          td
            = f.text_field "cell#{num * 5 + 2}".to_sym, list: "deliver_work", class: "cell", value: table.cells[num * 5 + 2], :size=>"28"
            datalist#deliver_work
              - @deliver_works.each do |deliver_work|
                |  <option value="
                = deliver_work.name
                | 　(
                = deliver_work.time_required
                | 分)">
          td
            = f.text_field "cell#{num * 5 + 3}".to_sym, list: "product_management_work", class: "cell", value: table.cells[num * 5 + 3], :size=>"28"
            datalist#product_management_work
              - @product_management_works.each do |product_management_work|
                |  <option value="
                = product_management_work.name
                | 　(
                = product_management_work.time_required
                | 分)">
          td
            = f.text_field "cell#{num * 5 + 4}".to_sym, list: "cleaning_work", class: "cell", value: table.cells[num * 5 + 4], :size=>"28"
            datalist#cleaning_work
              - @cleaning_works.each do |cleaning_work|
                |  <option value="
                = cleaning_work.name
                | 　(
                = cleaning_work.time_required
                | 分)">

app/views/tables/_row_time.html.slim
- if num % 4 == 0
  - if num > 75
    = num / 4 - 18
    | :00 
  - else
    = num / 4 + 6
    | :00 

app/views/tables/edit.html.slim
= form_with url: table_path( @table), method: :patch, local: true do |f|
  .page_header_margin_bottom_20px
    h1.page_title
      | 作業割当
  .vertically_aligned_and_centered
    h2
      | 編集
    h3.margin_top_0
      = f.label :name ,"タイトル"
      | ：
      = f.text_field :title, value: @table.title
      | 　
      = f.hidden_field :cells_length, value: @table.size * 5
      = f.hidden_field :table_size, value: @table.size
      = f.submit "保存", id: "submit_save"
  = render 'tables/form', f: f, table: @table

app/views/tables/index.html.slim
.page_header_margin_bottom_50px
  h1.page_title
    | 作業割当
= render 'shared/search_results'
.search_form
  = form_with url: search_table_path, method: :get, local: true do |f|
    = f.text_field :keyword, placeholder: "キーワードを入力"
    = f.submit :検索, id: "commit_search"
.centered
  p
    |  ※印刷したい場合は詳細ページに移動し、右上の「印刷」リンクをクリックしてください。 
.centered
  table.table_index
    thead
      tr
        th
          = sort_order "id", "id"
        th
          = sort_order "title", "タイトル"
        th
          = sort_order "updated_at", "更新日"
        th
          = sort_order "created_at", "作成日"
        th
          | 詳細
        th
          | 編集
        th
          | 複製
        th
          | 削除
    tbody
      - @tables.each do |table|
        tr
          td
            = table.id
          td
            = table.title
          td
            = table.updated_at.to_s(:datetime_jp)
          td
            = table.created_at.to_s(:datetime_jp)
          td
            = link_to "詳細", table_path(table.id), class: "color_blue", id: "show_table_#{table.id}", data: {"turbolinks" => false}
          td
            = link_to "編集", edit_table_path(table.id), class: "color_blue", id: "edit_table_#{table.id}", data: {"turbolinks" => false}
          td
            = link_to "複製", clone_table_path(table.id), class: "color_blue", id: "clone_table_#{table.id}", data: {"turbolinks" => false}
          td
            = link_to "削除", table_path(table.id), method: :delete, data: { confirm: "本当に削除しますか？", "turbolinks" => false }, class: "color_blue", id: "delete_table_#{table.id}"

app/views/tables/new.html.slim
= form_with url: tables_path, method: :post, local: true do |f|
  .page_header_margin_bottom_20px
    h1.page_title
      | 作業割当
  .vertically_aligned_and_centered
    .sample_data_link_area
      = link_to "サンプルデータを呼び出す", { call_sample: true }, class: "green_button", id: "set_sample_data_tables", data: {"turbolinks" => false}
    h2
      | 新規作成
    h3.margin_top_0
      = f.label :title ,"タイトル"
      | ：
      = f.text_field :title, value: @table.title
      | 　
      = f.hidden_field :cells_length, value: @table.size * 5
      = f.hidden_field :table_size, value: @table.size
      = f.submit "保存", id: "submit_save"
  = render 'tables/form', f: f, table: @table

app/views/tables/show.html.slim
.upper_right
  = link_to "戻る", tables_path, class:'green_button_print_hidden', data: {"turbolinks" => false}
  a.green_button_print_hidden[onclick="window.print();"]
    | 印刷
.page_header_margin_bottom_20px
  h1.page_title
    = @table.title
.centered
  table.sagyouwariate
    thead
      tr
        th
          | 時間
        th
          | 定時業務
        th
          | 納品業務
        th
          | 商品管理業務
        th
          | 清掃業務
    tbody
      - @rows.each do |row|
        tr
          td
            = row[0]
          td
            = row[1]
          td
            = row[2]
          td
            = row[3]
          td
            = row[4]